### ISSUE TITLE
...return value of "me.truemb.discordnotify.utils.UTF8YamlConfiguration.getConfigurationSection(String)" is null

### ISSUE THREAD

**Issue by RealKomander** [TrueMB/DiscordNotify#13]
Thanks for solving a simmilar error, but now I get this every few minutes
It looks like another db issue, I just don't understand what to do
```
[15:09:49 ERROR] [Spicord]: [JDA:JDA] One of the EventListeners had an uncaught exception
[15:09:49 ERROR]: java.lang.NullPointerException: Cannot invoke "org.simpleyaml.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "me.truemb.discordnotify.utils.UTF8YamlConfiguration.getConfigurationSection(String)" is null
[15:09:49 ERROR]:       at me.truemb.discordnotify.discord.listener.DC_ChatListener.onMessageReceived(DC_ChatListener.java:79)
[15:09:49 ERROR]:       at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483)
[15:09:49 ERROR]:       at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[15:09:49 ERROR]:       at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
[15:09:49 ERROR]:       at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
[15:09:49 ERROR]:       at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:160)
[15:09:49 ERROR]:       at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:123)
[15:09:49 ERROR]:       at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
[15:09:49 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
[15:09:49 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
[15:09:49 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
[15:09:49 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
[15:09:49 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
[15:09:49 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
[15:09:49 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
[15:09:49 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
[15:09:49 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
[15:09:49 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[15:09:49 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by TrueMB** [comment]
Could you send me the Chat Option Section of your config?
![grafik](https://user-images.githubusercontent.com/25579052/225333780-d26ae7c8-547f-43bb-9f37-5fc3cc33122d.png)

**Comment by RealKomander** [comment]
![image](https://user-images.githubusercontent.com/124439290/225688560-1659c461-294f-4225-98ee-4f43622b0643.png)

**Comment by RealKomander** [comment]
I haven't done anything, now for some reason it only spams this:

```
[13:38:39 ERROR] [Spicord]: [JDA:JDA] One of the EventListeners had an uncaught exception
[13:38:39 ERROR]: java.lang.NullPointerException
```

I'm sure it's still related to discordnotify

**Comment by TrueMB** [comment]
Sorry for no response so far. My time is currently limited.
And thanks for keeping me up-to-date!

I will try in the next few days, to find the issue.

Are you using Bungeecord or only Spigot?

**Comment by RealKomander** [comment]
I'm using velocity, all of my servers are paper

**Comment by TrueMB** [comment]
I am sorry once again for this long waiting time. But I think I know the problem, why this isn't working for you. Please put after **serverSeperatedChat:** the following brackets: **{}**

Leaving the whole thing blank breaks the config.

Also try the following Version.

[DiscordNotify-3.3.2-dev2.zip](https://github.com/TrueMB/DiscordNotify/files/11259420/DiscordNotify-3.3.2-dev2.zip)
