### ISSUE TITLE
[ISSUE] Couldn't pass PlayerChatEvent to discordnotify 3.3.5

### ISSUE THREAD

**Issue by SevensRequiem** [TrueMB/DiscordNotify#21]
java.lang.IllegalArgumentException: Failed to parse webhook URL
at me.truemb.discordnotify.utils.DiscordManager.createWebhookClientBuilder(DiscordManager.java:225) ~[?:?]
at me.truemb.discordnotify.utils.DiscordManager.createOrLoadWebhook(DiscordManager.java:244) ~[?:?]
at me.truemb.discordnotify.listener.DiscordNotifyListener.onPlayerMessageFeature(DiscordNotifyListener.java:455) ~[?:?]
at me.truemb.discordnotify.listener.DiscordNotifyListener.onPlayerMessage(DiscordNotifyListener.java:327) ~[?:?]
at me.truemb.universal.minecraft.events.VelocityEventsListener.onChat(VelocityEventsListener.java:40) ~[?:?]
at me.truemb.universal.minecraft.events.Lmbda$21.execute(Unknown Source) ~[?:?]
at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.3.0-SNAPSHOT-404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.3.0-SNAPSHOT-404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by TrueMB** [comment]
You are most likely using the Chat Feature with the Webhook Setting. But only placed the channel ID and not the webhook URL in the settings.

**Comment by SevensRequiem** [comment]
> You are most likely using the Chat Feature with the Webhook Setting. But only placed the channel ID and not the webhook URL in the settings.

What other options are there besides WEBHOOK? The wiki will not load for me

**Comment by TrueMB** [comment]
![grafik](https://github.com/TrueMB/DiscordNotify/assets/25579052/6c98f4f9-1fa8-4992-aa22-123f46e7c0dc)


Embed and Message are using the channel Id.
