### ISSUE TITLE
Error when using command

### ISSUE THREAD

**Issue by GlobusOk** [TrueMB/DiscordNotify#8]
Error when using command on server
[16:08:06] [Server thread/INFO]: GlobusOk issued server command: /rentit reload
[16:08:06] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rentit' in plugin RentIt v2.5.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:825) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1956) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1795) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1776) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1190) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:131) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1169) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1162) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1146) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1051) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3454-Spigot-ffceeae-74c0831]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.truemb.rentit.utils.UtilMethodes.isSubCommandEnabled(String, String)" because the return value of "me.truemb.rentit.main.Main.getMethodes()" is null
        at me.truemb.rentit.commands.RentItCOMMAND.onCommand(RentItCOMMAND.java:44) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more
![2022-03-12_15 14 34](https://user-images.githubusercontent.com/81820782/158019334-22dec994-888b-4d57-9537-f381d6f02a28.png)

There are many plugins on the server.
spigot-1.18.2
RentIt-2.5.3-dev2.jar

**Comment by TrueMB** [comment]
Could you send me the whole log since the server start?

**Comment by TrueMB** [comment]
Also this is not the right plugin repository...
